deploymentMode: SingleBinary

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem

singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

read:
  replicas: 0

write:
  replicas: 0

backend:
  replicas: 0

persistence:
  enabled: true
  size: 5Gi

chunksCache:
  enabled: false

resultsCache:
  enabled: false
